[2022-01-10T15:27:44.156] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:27:44.158] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:27:44.170] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.172] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.195] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.206] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.240] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.255] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:27:44.365] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.373] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.380] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.387] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:27:44.396] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:41.183] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:41.185] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.420] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.431] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:27:41.200] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:41.202] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.452] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:27:44.481] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:27:44.483] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:27:44.493] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:27:44.494] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:27:44.496] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:27:44.498] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:27:44.501] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.505] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.511] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:27:44.513] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:27:44.525] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:27:44.527] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:27:44.542] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:27:44.543] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:27:44.561] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:27:44.564] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:27:44.565] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:27:44.569] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:27:44.587] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:27:44.591] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:44.621] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:27:44.622] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:27:44.624] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:27:44.625] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:27:44.635] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:27:44.637] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:27:44.645] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:27:44.648] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:27:44.656] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:27:44.657] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:27:44.660] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:27:44.671] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:27:44.673] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:27:44.681] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:27:44.683] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:27:44.686] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:27:44.764] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:27:44.766] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:27:44.795] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:27:44.796] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:27:44.812] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:27:44.814] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:27:44.822] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:27:44.823] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:27:44.832] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:27:44.837] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:27:44.845] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:27:44.846] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:27:44.855] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:27:44.857] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:27:44.858] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:27:44.860] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:27:44.870] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:27:44.872] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:27:44.879] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:27:44.880] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:27:44.883] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:27:44.897] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:27:44.898] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:27:44.902] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:27:44.905] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:27:44.908] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:27:44.921] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:27:44.923] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:27:44.925] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:27:44.938] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:27:44.940] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:27:44.967] [ERROR] ma-core - 
[2022-01-10T15:27:45.028] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:27:45.029] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:27:45.032] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:27:45.048] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:27:45.052] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:27:45.053] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:27:45.060] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.070] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:27:45.073] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:27:45.090] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:27:45.092] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:27:45.093] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:27:45.104] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:27:45.106] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:27:45.119] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.125] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:27:45.126] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:27:45.131] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:27:45.133] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:27:45.141] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:27:45.143] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:27:45.159] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:27:45.161] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:27:45.262] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.285] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.310] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:27:45.340] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:27:45.346] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:27:45.347] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:27:45.354] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:27:45.466] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:27:45.471] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:27:45.487] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:27:45.491] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:27:45.524] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:27:45.526] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:27:45.544] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:27:45.546] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:27:45.593] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:27:45.612] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.614] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.627] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.628] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.640] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.642] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.655] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.657] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.670] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.673] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.677] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:27:45.680] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:27:45.693] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:27:45.693] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:27:45.696] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:27:45.697] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:27:45.716] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:27:45.723] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:27:45.807] [ERROR] ma-core - random Error
[2022-01-10T15:27:46.523] [ERROR] ma-core - random error
[2022-01-10T15:36:31.845] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:36:31.848] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:36:31.860] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.862] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.890] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.898] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.940] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:31.957] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:36:32.076] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.085] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.092] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.099] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:36:32.111] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:29.585] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:29.587] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.137] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.150] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:36:29.601] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:29.602] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.174] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:36:32.208] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:36:32.210] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:36:32.224] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:36:32.226] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:36:32.227] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:36:32.228] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:36:32.233] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.237] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.243] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:36:32.245] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:36:32.260] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:36:32.261] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:36:32.276] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:36:32.277] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:36:32.303] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:36:32.306] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:36:32.307] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:36:32.309] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:36:32.328] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:36:32.334] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.366] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:36:32.368] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:36:32.371] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:36:32.372] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:36:32.382] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:36:32.384] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:36:32.388] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:36:32.391] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:36:32.405] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:36:32.407] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:36:32.409] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:36:32.422] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:36:32.423] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:36:32.432] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:36:32.433] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:36:32.436] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:36:32.525] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:36:32.526] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:36:32.557] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:36:32.559] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:36:32.575] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:36:32.578] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:36:32.586] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:36:32.588] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:36:32.597] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:36:32.599] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:36:32.607] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:36:32.611] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:36:32.622] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:36:32.623] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:36:32.625] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:36:32.626] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:36:32.637] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:36:32.639] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:36:32.645] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:36:32.647] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:36:32.651] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:36:32.666] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:36:32.669] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:36:32.671] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:36:32.675] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:36:32.677] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:36:32.691] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:36:32.693] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:36:32.695] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:36:32.705] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:36:32.706] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:36:32.742] [ERROR] ma-core - 
[2022-01-10T15:36:32.805] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:36:32.807] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:36:32.809] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:36:32.823] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:36:32.825] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:36:32.826] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:36:32.840] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.851] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:36:32.854] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:36:32.872] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:36:32.873] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:36:32.875] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:36:32.887] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:36:32.888] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:36:32.901] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:32.908] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:36:32.909] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:36:32.915] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:36:32.917] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:36:32.925] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:36:32.927] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:36:32.939] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:36:32.944] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:36:33.057] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.080] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.107] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:36:33.130] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:36:33.144] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:36:33.145] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:36:33.154] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:36:33.265] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:36:33.270] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:36:33.279] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:36:33.281] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:36:33.298] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:36:33.301] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:36:33.311] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:36:33.313] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:36:33.385] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:36:33.410] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.412] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.425] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.427] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.436] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.438] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.446] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.450] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.459] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.460] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.465] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:36:33.470] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:36:33.477] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:36:33.478] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:36:33.485] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:36:33.486] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:36:33.509] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:36:33.512] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:36:33.587] [ERROR] ma-core - random Error
[2022-01-10T15:36:34.293] [ERROR] ma-core - random error
[2022-01-10T15:37:29.665] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:37:29.668] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:37:29.681] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.683] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.709] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.717] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.757] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.773] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-01-10T15:37:29.915] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.923] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.931] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.938] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-01-10T15:37:29.949] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:27.486] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:27.489] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:29.974] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:29.985] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-01-10T15:37:27.508] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:27.510] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:30.002] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-01-10T15:37:30.032] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-01-10T15:37:30.033] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-01-10T15:37:30.047] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-01-10T15:37:30.048] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-01-10T15:37:30.049] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:37:30.051] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:37:30.054] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.059] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.066] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-01-10T15:37:30.067] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-01-10T15:37:30.081] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-01-10T15:37:30.083] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-01-10T15:37:30.096] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-01-10T15:37:30.097] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-01-10T15:37:30.117] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-01-10T15:37:30.119] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:37:30.121] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-01-10T15:37:30.125] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-01-10T15:37:30.144] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-01-10T15:37:30.151] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.182] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-01-10T15:37:30.183] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-01-10T15:37:30.185] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:37:30.187] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-01-10T15:37:30.197] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-01-10T15:37:30.198] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-01-10T15:37:30.202] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-01-10T15:37:30.205] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-01-10T15:37:30.213] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:37:30.215] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-01-10T15:37:30.217] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-01-10T15:37:30.230] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-01-10T15:37:30.231] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-01-10T15:37:30.239] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:37:30.241] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-01-10T15:37:30.244] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-01-10T15:37:30.325] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-01-10T15:37:30.327] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-01-10T15:37:30.361] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-01-10T15:37:30.362] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-01-10T15:37:30.379] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-01-10T15:37:30.381] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-01-10T15:37:30.388] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-01-10T15:37:30.391] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-01-10T15:37:30.400] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-01-10T15:37:30.401] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-01-10T15:37:30.409] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-01-10T15:37:30.410] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-01-10T15:37:30.419] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-01-10T15:37:30.421] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-01-10T15:37:30.423] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:37:30.425] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-01-10T15:37:30.434] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-01-10T15:37:30.437] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-01-10T15:37:30.444] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:37:30.446] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-01-10T15:37:30.454] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-01-10T15:37:30.468] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-01-10T15:37:30.469] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-01-10T15:37:30.472] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-01-10T15:37:30.476] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-01-10T15:37:30.479] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-01-10T15:37:30.495] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:37:30.497] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-01-10T15:37:30.499] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-01-10T15:37:30.510] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-01-10T15:37:30.511] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-01-10T15:37:30.538] [ERROR] ma-core - 
[2022-01-10T15:37:30.604] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:37:30.606] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-01-10T15:37:30.609] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-01-10T15:37:30.619] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:37:30.622] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-01-10T15:37:30.624] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-01-10T15:37:30.631] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.643] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-01-10T15:37:30.645] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-01-10T15:37:30.663] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:37:30.665] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-01-10T15:37:30.666] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-01-10T15:37:30.682] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-01-10T15:37:30.684] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-01-10T15:37:30.696] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.703] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-01-10T15:37:30.705] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-01-10T15:37:30.710] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-01-10T15:37:30.712] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-01-10T15:37:30.720] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-01-10T15:37:30.721] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-01-10T15:37:30.733] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-01-10T15:37:30.735] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-01-10T15:37:30.841] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.867] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.896] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-01-10T15:37:30.919] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:37:30.927] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-01-10T15:37:30.928] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-01-10T15:37:30.934] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-01-10T15:37:31.052] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-01-10T15:37:31.057] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-01-10T15:37:31.068] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-01-10T15:37:31.070] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-01-10T15:37:31.088] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-01-10T15:37:31.090] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-01-10T15:37:31.102] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-01-10T15:37:31.103] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:37:31.171] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-01-10T15:37:31.187] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.189] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.197] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.199] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.207] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.209] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.217] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.218] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.226] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.228] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.231] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-01-10T15:37:31.235] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-01-10T15:37:31.244] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-01-10T15:37:31.244] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-01-10T15:37:31.247] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-01-10T15:37:31.247] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-01-10T15:37:31.261] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-01-10T15:37:31.264] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-01-10T15:37:31.337] [ERROR] ma-core - random Error
[2022-01-10T15:37:32.024] [ERROR] ma-core - random error
